version: '3'
services:
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'Admin@123'
            MYSQL_USER: 'cuikho210'
            MYSQL_PASSWORD: 'ckckck'
            MYSQL_DATABASE: 'mtlkms'
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 3306:3306